/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : sShrimp
**     Processor   : MKE06Z128VLK4
**     Component   : MKE06Z128LK4
**     Version     : Component 01.011, Driver 01.00, CPU db: 3.00.000
**     Datasheet   : MKE06P80M48SF0RM, Rev. 1, Dec 2013
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-04-20, 14:55, # CodeGen: 126
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         No public methods
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* MQX Lite include files */
#include "mqxlite.h"
#include "mqxlite_prv.h"
#include "Cpu.h"
#include "Events.h"
#include "mqx_tasks.h"
#include "Init_Config.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  Common_Init (component MKE06Z128LK4)
**     Description :
**         Initialization of registers for that there is no 
**         initialization component.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMMON_INIT
void Common_Init(void)
{
  /* Common initialization of registers which initialization is required 
     for proper functionality of components in the project but initialization
     component which would be configuring these registers is missing 
     in the project. 
     Add associated initialization component to the project to avoid 
     initialization of registers in the Common_Init().
     Also, after reset value optimization property affects initialization of 
     registers in this method (see active generator configuration 
     Optimizations\Utilize after reset values property or enabled processor 
     component Common settings\Utilize after reset values property) */
  /* SIM_PINSEL1: UART1PS=0 */
  SIM_PINSEL1 &= (uint32_t)~(uint32_t)(SIM_PINSEL1_UART1PS_MASK);
  /* SIM_SOPT0: NMIE=1 */
  SIM_SOPT0 |= SIM_SOPT0_NMIE_MASK;
  /* PORT_HDRVE: PTB4=0 */
  PORT_HDRVE &= (uint32_t)~(uint32_t)(PORT_HDRVE_PTB4_MASK);
  /* PORT_PUE0: PTDPE5=0,PTBPE4=0 */
  PORT_PUE0 &= (uint32_t)~(uint32_t)(
                PORT_PUE0_PTDPE5_MASK |
                PORT_PUE0_PTBPE4_MASK
               );
  /* PORT_PUE1: PTGPE0=1 */
  PORT_PUE1 |= PORT_PUE1_PTGPE0_MASK;
  /* PORT_PUE2: PTIPE6=1 */
  PORT_PUE2 |= PORT_PUE2_PTIPE6_MASK;
}

#endif /* CPU_COMMON_INIT */

/*
** ===================================================================
**     Method      :  Components_Init (component MKE06Z128LK4)
**     Description :
**         Initialization of components (with exception for Peripheral
**         Initialization Components which are initialized in 
**         Peripherals_Init() method).
**         For example, if automatic initialization feature 
**         is enabled in LDD component then its Init method call 
**         is executed in Components_Init() method.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMPONENTS_INIT
void Components_Init(void)
{
  /* ### BitIO_LDD "MB_NRST" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
  (void)MB_NRST_Init(NULL);
  /* ### BitIO_LDD "MB_NPW" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
  (void)MB_NPW_Init(NULL);
  /* ### BitIO_LDD "MB_DTR" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
  (void)MB_DTR_Init(NULL);
  /* ### Serial_LDD "IO1" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
  (void)IO1_Init(NULL);
  /* ### ExtInt_LDD "MB_RI" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
  (void)MB_RI_Init(NULL);
  /* ### BitIO_LDD "MB_STATUS" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
  (void)MB_STATUS_Init(NULL);
}
#endif /* CPU_COMPONENTS_INIT */


#ifdef __cplusplus
}
#endif

/* END Cpu. */

